language: crystal

script:
  - crystal spec
  - crystal tool format --check
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: hour
  on:
    branch: master
  local_dir: docs

# https://docs.travis-ci.com/user/notifications
notifications:
  email: no
